import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import pc from 'picocolors'
import {
  TRANSLATION_LANGUAGES,
  DEFAULT_TRANSLATION_TIER,
  TRANSLATION_CDN_ORIGIN,
  TRANSLATION_CDN_BASE_KEY,
  TRANSLATION_CDN_BUCKET_PREFIX,
} from '../constants.js'

export interface I18nPullOptions {
  phase: string
  tier: string
  ref: string
  out: string
  /** 번역 시스템 — 유저 플랫폼('user') vs 어드민 플랫폼('admin'). 키 프리픽스가 다르다(B vs A). */
  target: string
}

type Dict = Record<string, string>

/** latest.json 응답 — 실제 번역 파일이 놓인 버전 경로(cdnPath)를 가리킨다. */
interface LatestManifest {
  version: string
  cdnPath: string
}

/**
 * latest.json 키. 기본 tier는 세그먼트가 없고, 그 외 tier는 경로에 tier가 들어간다.
 * `target`은 번역 시스템 세그먼트(user/admin) — 유저·어드민 모두 동일한 구조를 쓴다.
 * (hub TranslationService.fetchLatest / 어드민 플랫폼 get-languages와 동일 규칙)
 */
function latestKey(phase: string, tier: string, target: string): string {
  const segments =
    tier === DEFAULT_TRANSLATION_TIER
      ? [TRANSLATION_CDN_BASE_KEY, phase, target]
      : [TRANSLATION_CDN_BASE_KEY, phase, target, tier]
  return [...segments, 'latest.json'].join('/')
}

/** CDN 캐시를 우회하기 위한 5분 단위 스탬프 (hub getLegacyStamp와 동일). */
function cacheStamp(now: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0')
  const date = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}-${pad(now.getHours())}`
  const min = now.getMinutes()
  const floored = min - (min % 5)
  return `${date}-${pad(floored)}`
}

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  return (await res.json()) as T
}

/** JSDoc 주석 안에 안전하게 넣도록 정리한다(주석 종료 시퀀스 차단, 개행 제거). */
function escapeJsdoc(value: string): string {
  return value.replace(/\*\//g, '*\\/').replace(/\r?\n/g, ' ').trim()
}

/**
 * ref 로케일 사전으로 타입 모듈을 생성한다.
 *
 * - TranslationKeyRegistry declaration merging → useBstageTranslations().t()의 키가 좁혀짐
 * - bstageTranslationKeys 상수(원문 JSDoc) → 호버로 의미 확인, 코드 내 원문 검색
 */
function generateTypeModule(dict: Dict, meta: { version: string; ref: string }): string {
  const keys = Object.keys(dict).sort()
  // 레지스트리 멤버에도 원문 JSDoc을 단다 → t() 키 자동완성 시 문서 패널에 원문이 보인다.
  const registry = keys
    .map((k) => `    /** ${escapeJsdoc(dict[k])} */\n    ${JSON.stringify(k)}: true`)
    .join('\n')
  const consts = keys
    .map((k) => `  /** ${escapeJsdoc(dict[k])} */\n  ${JSON.stringify(k)}: ${JSON.stringify(k)},`)
    .join('\n')

  return `// AUTO-GENERATED by \`bstage i18n pull\` — 직접 수정하지 마세요.
// version: ${meta.version} (ref=${meta.ref}, 키 ${keys.length}개)
/* eslint-disable */

declare module '@bstage-sdk/core' {
  interface TranslationKeyRegistry {
${registry}
  }
}

/** 플랫폼 번역 키 → 코드. 호버로 원문 확인, 코드 내 원문 검색에 사용한다. */
export const bstageTranslationKeys = {
${consts}
} as const
`
}

/**
 * `bstage i18n pull` — CDN에서 플랫폼 번역 사전을 직접 받아(Hub·인증 우회)
 * (1) 타입 모듈 생성, (2) 로컬 캐시 저장.
 */
export async function i18nPullCommand(options: I18nPullOptions): Promise<void> {
  const root = process.cwd()
  const tier = options.tier || DEFAULT_TRANSLATION_TIER
  const target = options.target || 'user'

  // 1) latest.json → 버전 경로(cdnPath)
  const latestUrl = `${TRANSLATION_CDN_ORIGIN}/${latestKey(options.phase, tier, target)}?date=${cacheStamp(new Date())}`
  console.log(pc.cyan(`[bstage] 번역 pull: ${options.phase}/${target} (tier=${tier})`))

  let latest: LatestManifest
  try {
    latest = await fetchJson<LatestManifest>(latestUrl)
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err)
    console.error(pc.red(`[bstage] latest.json 조회 실패: ${msg}\n  ${latestUrl}`))
    process.exit(1)
  }

  const versionBase = `${TRANSLATION_CDN_ORIGIN}/${latest.cdnPath.replace(TRANSLATION_CDN_BUCKET_PREFIX, '')}`
  console.log(pc.dim(`  version: ${latest.version}`))

  // 2) 로케일별 사전 → 캐시
  // target별로 나눈다 — 한 프로젝트가 user·admin 사전을 모두 받을 수 있고, 한 디렉토리를 쓰면
  // 나중에 받은 쪽이 앞의 것을 덮어써 원문 검색이 반쪽이 된다(타입 파일만 `--out`으로 갈렸다).
  const cacheDir = join(root, '.bstage', 'i18n', target)
  mkdirSync(cacheDir, { recursive: true })

  let refDict: Dict | null = null
  const fetched: string[] = []
  for (const locale of TRANSLATION_LANGUAGES) {
    try {
      const dict = await fetchJson<Dict>(`${versionBase}/${locale}/translation.json`)
      writeFileSync(join(cacheDir, `${locale}.json`), JSON.stringify(dict, null, 2))
      fetched.push(locale)
      if (locale === options.ref) refDict = dict
      console.log(pc.green(`  ✓ ${locale} (${Object.keys(dict).length})`))
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err)
      console.warn(pc.yellow(`  - ${locale}: ${msg} — 건너뜀`))
    }
  }

  if (fetched.length === 0) {
    console.error(pc.red('[bstage] 받은 번역이 없습니다.'))
    process.exit(1)
  }

  if (!refDict) {
    console.warn(
      pc.yellow(`[bstage] ref 로케일(${options.ref}) 사전이 없어 타입 생성을 건너뜁니다.`),
    )
    return
  }

  // 3) 타입 모듈 생성
  const outPath = resolve(root, options.out)
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, generateTypeModule(refDict, { version: latest.version, ref: options.ref }))

  console.log(pc.green(`[bstage] 타입 생성: ${options.out} (${Object.keys(refDict).length} 키)`))
  console.log(
    pc.dim(
      `  캐시: .bstage/i18n/${target}/*.json — 타입 생성 입력 + 원문 검색용(런타임은 CDN에서 직접 받는다)`,
    ),
  )
  console.log(pc.dim('  생성 파일을 한 번 import하면 useBstageTranslations().t() 키가 좁혀집니다.'))
}
