export {
  HttpClient,
  HttpError,
  HttpTimeoutError,
  type FetchFunction,
  type HttpClientConfig,
  type HttpMethod,
  type HttpResponse,
  type RequestConfig,
  type RequestInterceptor,
  type ResponseInterceptor,
} from './http/index.js'

export {
  BstageClient,
  type BstageConfig,
  type PathParams,
  type RequestOptions,
  type QueryRequestOptions,
  type BodyRequestOptions,
} from './client/index.js'

export type {
  BoardInfo,
  BoardPostInfo,
  Content,
  ContentsSectionInfo,
  DigitalTicket,
  Product,
} from './domain.js'

export {
  LANGUAGES,
  DEFAULT_LANGUAGE,
  normalizeLanguage,
  readLocale,
  observeLocale,
  fetchTranslations,
  interpolateTranslation,
  configureBstageI18n,
  resolveTranslationChain,
  pickTranslation,
  parseRichText,
  type RichTextToken,
  type BstageI18nConfig,
  type LanguageCode,
  type LocaleTarget,
  type TranslationPhase,
  type TranslationDict,
  type TranslateParams,
  type TranslationKey,
  type TranslationKeyRegistry,
} from './i18n.js'

export {
  PlatformBridge,
  createWebComponent,
  SLOT_CATALOG,
  getSlotsByTarget,
  SLOT_CATALOG_V2,
  getSlotsByTargetV2,
  slotIdToDirName,
  dirNameToSlotId,
  isSlotIdV2,
  ADMIN_EVENT_CATALOG,
  getAdminEventsByDomain,
  announceElementName,
  lookupElementName,
  __resetElementRegistry__,
  type FrameworkAdapter,
  type PlatformEventHandler,
  type TemplateEventMap,
  type TemplateEventType,
  type PlatformEventMap,
  type PlatformEventType,
  type AdminDomainEventType,
  type AdminDomainEventMap,
  type TicketCreateAfterPayload,
  type SlotContextPayload,
  type AdminConnectPayload,
  type TemplateSlot,
  type CustomSlots,
  type TemplateOptions,
  type SlotIdV2,
  type SlotCatalogEntryV2,
  type SlotContextOf,
  type SlotContextMap,
  type SlotContextOverrides,
  type CustomSlotsV2,
} from './core/index.js'
