// AUTO-GENERATED by `pnpm gen:tokens` — 직접 수정하지 마세요.
// 원본(SSOT): b.stage 디자인 시스템의 user 토큰 정의
/* eslint-disable */

import type { ColorPair, ShadowPair, TypographyValue } from '../shared/types.js'

/** 다크모드 대응 색 토큰 (light/dark 쌍) → --user-mode-* */
export const modeColors = {
  "bg/base": {
    "dark": "#151515",
    "light": "#ffffff"
  },
  "bg/blue-grey": {
    "dark": "#1f2023",
    "light": "#eff1f7"
  },
  "bg/elevated": {
    "dark": "#232323",
    "light": "#ffffff"
  },
  "bg/grouped-strong": {
    "dark": "#000000",
    "light": "#f7f7f7"
  },
  "bg/grouped-weak": {
    "dark": "#111111",
    "light": "#f7f7f7"
  },
  "bg/grouped-weak-a": {
    "dark": "#ffffff0f",
    "light": "#0000000f"
  },
  "bg/highlight": {
    "dark": "#2f2f2f",
    "light": "#e6e6e6"
  },
  "bg/invert-weak-a": {
    "dark": "#00000026",
    "light": "#ffffff26"
  },
  "border/blue": {
    "dark": "#0090ff",
    "light": "#148aff"
  },
  "border/blue-weak-a": {
    "dark": "#0090ff4d",
    "light": "#148aff4d"
  },
  "border/default-a": {
    "dark": "#ffffff1a",
    "light": "#0000001a"
  },
  "border/divider-weaker": {
    "dark": "#0d0d0d",
    "light": "#f7f7f7"
  },
  "border/green": {
    "dark": "#0be06f",
    "light": "#00b84d"
  },
  "border/green-weak-a": {
    "dark": "#0be06f4d",
    "light": "#00b84d4d"
  },
  "border/grey": {
    "dark": "#b3b3b3",
    "light": "#7a7a7a"
  },
  "border/grey-weak-a": {
    "dark": "#b3b3b34d",
    "light": "#7a7a7a4d"
  },
  "border/invert": {
    "dark": "#0d0d0d",
    "light": "#ffffff"
  },
  "border/red": {
    "dark": "#ff4747",
    "light": "#ff4a40"
  },
  "border/red-weak-a": {
    "dark": "#ff47474d",
    "light": "#ff4a404d"
  },
  "border/strong-a": {
    "dark": "#ffffff33",
    "light": "#00000033"
  },
  "border/stronger": {
    "dark": "#eeeeee",
    "light": "#454545"
  },
  "border/weak-a": {
    "dark": "#ffffff0a",
    "light": "#0000000f"
  },
  "border/yellow": {
    "dark": "#f5b625",
    "light": "#f29900"
  },
  "border/yellow-weak-a": {
    "dark": "#f5b6254d",
    "light": "#f299004d"
  },
  "icon/blue": {
    "dark": "#0090ff",
    "light": "#148aff"
  },
  "icon/green": {
    "dark": "#0be06f",
    "light": "#00b84d"
  },
  "icon/grey": {
    "dark": "#b3b3b3",
    "light": "#7a7a7a"
  },
  "icon/invert": {
    "dark": "#0d0d0d",
    "light": "#ffffff"
  },
  "icon/primary": {
    "dark": "#ffffff",
    "light": "#000000"
  },
  "icon/quaternary-a": {
    "dark": "#ffffff4d",
    "light": "#0000004d"
  },
  "icon/red": {
    "dark": "#ff4747",
    "light": "#ff4a40"
  },
  "icon/secondary-a": {
    "dark": "#ffffffba",
    "light": "#000000ba"
  },
  "icon/tertiary-a": {
    "dark": "#ffffff80",
    "light": "#00000080"
  },
  "icon/yellow": {
    "dark": "#f5b625",
    "light": "#f29900"
  },
  "overlay/hover-a": {
    "dark": "#ffffff14",
    "light": "#0000001a"
  },
  "overlay/hover-grey-a": {
    "dark": "#4545451a",
    "light": "#4545451a"
  },
  "overlay/press-a": {
    "dark": "#ffffff33",
    "light": "#00000026"
  },
  "overlay/press-grey-a": {
    "dark": "#45454526",
    "light": "#45454526"
  },
  "service/live": {
    "dark": "#e51a42",
    "light": "#e2012d"
  },
  "service/live-weak-a": {
    "dark": "#e51a4226",
    "light": "#e2012d4d"
  },
  "service/membership": {
    "dark": "#ffbf00",
    "light": "#ffb010"
  },
  "service/membership-weak-a": {
    "dark": "#ffbf001f",
    "light": "#eb91001f"
  },
  "service/noti": {
    "dark": "#0c198b",
    "light": "#020f81"
  },
  "service/pop-bg": {
    "dark": "linear-gradient(135deg, #3b3a2d 13.08%, #232732 87.56%)",
    "light": "linear-gradient(135deg, #faf7de 13.08%, #e7edfd 87.56%)"
  },
  "surface/card": {
    "dark": "#232323",
    "light": "#ffffff"
  },
  "surface/display-bar-bottom": {
    "dark": "#151515",
    "light": "#fdfdfd"
  },
  "surface/display-bar-top": {
    "dark": "#151515",
    "light": "#ffffff"
  },
  "surface/display-lock": {
    "dark": "#2f2f2f",
    "light": "#bfbfbf"
  },
  "surface/form-blue": {
    "dark": "#0090ff",
    "light": "#148aff"
  },
  "surface/form-blue-weak-a": {
    "dark": "#0f97ff1f",
    "light": "#007aff26"
  },
  "surface/form-gradient-h": {
    "dark": "linear-gradient(90deg, #151515 0%, #15151500 100%)",
    "light": "linear-gradient(90deg, #ffffff 0%, #ffffff00 100%)"
  },
  "surface/form-green": {
    "dark": "#00cc5f",
    "light": "#00bf59"
  },
  "surface/form-green-weak-a": {
    "dark": "#0be06f14",
    "light": "#00b84d26"
  },
  "surface/form-grey": {
    "dark": "#7a7a7a",
    "light": "#999999"
  },
  "surface/form-grey-weak-a": {
    "dark": "#b3b3b314",
    "light": "#6666661f"
  },
  "surface/form-inverted": {
    "dark": "#f7f7f7",
    "light": "#151515"
  },
  "surface/form-inverted-deep": {
    "dark": "#ffffff",
    "light": "#000000"
  },
  "surface/form-primary-a": {
    "dark": "#ffffff0f",
    "light": "#0000000f"
  },
  "surface/form-red": {
    "dark": "#ff4747",
    "light": "#ff4a40"
  },
  "surface/form-red-weak-a": {
    "dark": "#ff47471f",
    "light": "#ff4a4026"
  },
  "surface/form-secondary-a": {
    "dark": "#ffffff0a",
    "light": "#0000000a"
  },
  "surface/form-yellow": {
    "dark": "#f5b625",
    "light": "#f29900"
  },
  "surface/form-yellow-weak-a": {
    "dark": "#f5b62514",
    "light": "#f299001f"
  },
  "text/blue": {
    "dark": "#0090ff",
    "light": "#148aff"
  },
  "text/green": {
    "dark": "#0be06f",
    "light": "#00b84d"
  },
  "text/grey": {
    "dark": "#b3b3b3",
    "light": "#666666"
  },
  "text/invert-a": {
    "dark": "#000000ed",
    "light": "#ffffffed"
  },
  "text/primary": {
    "dark": "#eeeeee",
    "light": "#151515"
  },
  "text/primary-a": {
    "dark": "#ffffffed",
    "light": "#000000ed"
  },
  "text/quaternary": {
    "dark": "#777777",
    "light": "#999999"
  },
  "text/quaternary-a": {
    "dark": "#ffffff80",
    "light": "#00000080"
  },
  "text/red": {
    "dark": "#ff4747",
    "light": "#ff4a40"
  },
  "text/secondary": {
    "dark": "#bababa",
    "light": "#454545"
  },
  "text/secondary-a": {
    "dark": "#ffffffba",
    "light": "#000000ba"
  },
  "text/tertiary": {
    "dark": "#999999",
    "light": "#666666"
  },
  "text/tertiary-a": {
    "dark": "#ffffff99",
    "light": "#00000099"
  },
  "text/yellow": {
    "dark": "#f5b625",
    "light": "#f29900"
  }
} as const satisfies Record<string, ColorPair>

/** 테마 비의존 색 토큰 (always/auto/picker/pop) → --user-{group}-* */
export const flatColors = {
  "always/avatar-bg01": "#aa47bc",
  "always/avatar-bg02": "#7a1fa2",
  "always/avatar-bg03": "#7e57c2",
  "always/avatar-bg04": "#512da7",
  "always/avatar-bg05": "#5c6bc0",
  "always/avatar-bg06": "#0288d1",
  "always/avatar-bg07": "#00579c",
  "always/avatar-bg08": "#0098a6",
  "always/avatar-bg09": "#00887a",
  "always/avatar-bg10": "#689f39",
  "always/avatar-bg11": "#33691e",
  "always/avatar-bg12": "#004c3f",
  "always/avatar-bg13": "#ec407a",
  "always/avatar-bg14": "#c2175b",
  "always/avatar-bg15": "#bf360c",
  "always/avatar-bg16": "#f5511e",
  "always/avatar-bg17": "#ef6c00",
  "always/avatar-bg18": "#8c6e63",
  "always/avatar-bg19": "#5d4038",
  "always/avatar-bg20": "#78909c",
  "always/avatar-bg21": "#465a65",
  "always/black006-a": "#0000000f",
  "always/black010-a": "#0000001a",
  "always/black015-a": "#00000026",
  "always/black020-a": "#00000033",
  "always/black030-a": "#0000004d",
  "always/black050-a": "#00000080",
  "always/black060-a": "#00000099",
  "always/black080-a": "#000000cc",
  "always/black100": "#000000",
  "always/grey-strong": "#232323",
  "always/grey085": "#5c5c5c",
  "always/lightgrey006-a": "#9999990f",
  "always/lightgrey010-a": "#9999991a",
  "always/lightgrey015-a": "#99999926",
  "always/lightgrey020-a": "#99999933",
  "always/lightgrey030-a": "#9999994d",
  "always/lightgrey050-a": "#99999980",
  "always/lightgrey080-a": "#999999cc",
  "always/lightgrey100": "#999999",
  "always/palette05": "linear-gradient(135deg, #db2667 0%, #f4a368 100%)",
  "always/service-live-pop": "#df3868",
  "always/service-live-red": "#ff0000",
  "always/service-mnet": "#ff477f",
  "always/service-mnetapp": "#ff477f",
  "always/service-point": "linear-gradient(135deg, #1cac3c 0%, #1ca6bb 100%)",
  "always/service-pop-ing": "linear-gradient(135deg, #db2667 0%, #f4a368 100%)",
  "always/service-popgrey-weak-a": "#707ca00f",
  "always/service-post-thumb-a": "#aa89f5cc",
  "always/service-rankingpoll-thumb-a": "#FFADDD80",
  "always/service-red080-a": "#f5254acc",
  "always/service-survey": "#597eff",
  "always/service-survey-thumb-a": "#7192f5cc",
  "always/service-ticket": "#00bf59",
  "always/white006-a": "#ffffff0f",
  "always/white010-a": "#ffffff1a",
  "always/white015-a": "#ffffff26",
  "always/white020-a": "#ffffff33",
  "always/white030-a": "#ffffff4d",
  "always/white050-a": "#ffffff80",
  "always/white060-a": "#ffffff99",
  "always/white080-a": "#ffffffcc",
  "always/white100": "#ffffff",
  "auto/icon-primary-on-dark": "#ffffff",
  "auto/icon-primary-on-light": "#000000ed",
  "auto/icon-secondary-on-dark": "#ffffff",
  "auto/icon-secondary-on-light": "#000000ba",
  "auto/text-primary-on-dark": "#ffffff",
  "auto/text-primary-on-light": "#000000",
  "auto/text-secondary-on-dark": "#ffffffcc",
  "auto/text-secondary-on-light": "#000000cc",
  "picker/button": "#654bff",
  "picker/button-weak-a": "#654bff26",
  "picker/on-button": "#ffffff",
  "picker/star": "#7266ff",
  "pop/bg-tl01": "#c9d0ea",
  "pop/bg-tl02": "#f2de6f",
  "pop/bg-tl03": "#fca783",
  "pop/bg-tl04": "#a0dda6",
  "pop/bg-tl05": "#a2bce3",
  "pop/bg-tl06": "#f7b3cf",
  "pop/bg-tl07": "#bfa2e3",
  "pop/bg-tl08": "#fb8686",
  "pop/bg-tl09": "#eec2c2",
  "pop/bg-tl10": "#e2d1b0",
  "pop/bubble-tl01": "#7984b1",
  "pop/bubble-tl03": "#e3703f",
  "pop/bubble-tl04": "#5fac70",
  "pop/bubble-tl05": "#587ab1",
  "pop/bubble-tl06": "#ca7094",
  "pop/bubble-tl07": "#8067b5",
  "pop/bubble-tl08": "#cb4e4e",
  "pop/bubble-tl09": "#cb8181",
  "pop/bubble-tl1": "#a79272",
  "pop/item-gradient01": "linear-gradient(135deg, #fbf3ac 0%, #ffe1fc 100%)",
  "pop/item-gradient02": "linear-gradient(135deg, #cbe6ff 0%, #d5ffdf 100%)",
  "pop/item-gradient03": "linear-gradient(135deg, #e4ceff 0%, #ffe4cc 100%)",
  "pop/item-gradient04": "linear-gradient(135deg, #ffdcb3 0%, #c9f8ff 100%)",
  "pop/item-gradient05": "linear-gradient(135deg, #ffd0ec 0%, #d3fcff 100%)",
  "pop/item-gradient06": "linear-gradient(135deg, #feb5b5 0%, #d6fee1 100%)"
} as const satisfies Record<string, string>

/** 그림자 토큰 → --user-mode-shadow-* */
export const shadowTokens = {
  "shadow/default-large": {
    "dark": "0px 1px 2px 0px #00000033, 0px 8px 48px 0px #00000099",
    "light": "0px 1px 2px 0px #1a1a1a05, 0px 8px 48px 0px #1a1a1a26"
  },
  "shadow/default-medium": {
    "dark": "0px 1px 2px 0px #00000033, 0px 4px 24px 0px #00000066",
    "light": "0px 1px 2px 0px #00000005, 0px 4px 24px 0px #1a1a1a1a"
  },
  "shadow/default-small": {
    "dark": "0px 1px 2px 0px #0000001a, 0px 2px 8px 0px #00000066",
    "light": "0px 1px 2px 0px #1a1a1a05, 0px 2px 8px 0px #1a1a1a1a"
  },
  "shadow/default-xlarge": {
    "dark": "0px 1px 2px 0px #00000033, 0px 16px 72px 0px #00000099",
    "light": "0px 1px 2px 0px #1a1a1a05, 0px 16px 72px 0px #1a1a1a26"
  },
  "shadow/default-xsmall": {
    "dark": "0px 1px 2px 0px #00000033, 0px 0px 4px 0px #00000066",
    "light": "0px 1px 2px 0px #1a1a1a05, 0px 0px 4px 0px #1a1a1a26"
  },
  "shadow/weak-large": {
    "dark": "0px 1px 2px 0px #0000001a, 0px 8px 48px 0px #00000066",
    "light": "0px 1px 2px 0px #1a1a1a05, 0px 8px 48px 0px #1a1a1a1f"
  },
  "shadow/weak-medium": {
    "dark": "0px 1px 2px 0px #0000001a, 0px 4px 24px 0px #00000033",
    "light": "0px 1px 2px 0px #00000005, 0px 4px 20px 0px #1a1a1a14"
  },
  "shadow/weak-small": {
    "dark": "0px 1px 2px 0px #0000001a, 0px 2px 8px 0px #00000033",
    "light": "0px 1px 2px 0px #1a1a1a05, 0px 2px 8px 0px #1a1a1a14"
  },
  "shadow/weak-xlarge": {
    "dark": "0px 1px 2px 0px #0000001a, 0px 16px 72px 0px #00000066",
    "light": "0px 1px 2px 0px #1a1a1a05, 0px 16px 72px 0px #1a1a1a1f"
  },
  "shadow/weak-xsmall": {
    "dark": "0px 1px 2px 0px #0000001a, 0px 0px 4px 0px #00000033",
    "light": "0px 1px 1px 0px #1a1a1a05, 0px 0px 4px 0px #1a1a1a14"
  }
} as const satisfies Record<string, ShadowPair>

/** 타이포그래피 토큰 */
export const typographyTokens = {
  "10/caption": {
    "fontSize": "0.625rem",
    "letterSpacing": "0%",
    "lineHeight": "0.75rem"
  },
  "11/caption": {
    "fontSize": "0.6875rem",
    "letterSpacing": "0%",
    "lineHeight": "0.875rem"
  },
  "12/caption": {
    "fontSize": "0.75rem",
    "letterSpacing": "0%",
    "lineHeight": "1rem"
  },
  "13/body": {
    "fontSize": "0.8125rem",
    "letterSpacing": "0%",
    "lineHeight": "1.125rem"
  },
  "14/body": {
    "fontSize": "0.875rem",
    "letterSpacing": "0%",
    "lineHeight": "1.25rem"
  },
  "15/body": {
    "fontSize": "0.9375rem",
    "letterSpacing": "0%",
    "lineHeight": "1.375rem"
  },
  "15/title": {
    "fontSize": "0.9375rem",
    "letterSpacing": "0%",
    "lineHeight": "1.25rem"
  },
  "16/title": {
    "fontSize": "1rem",
    "letterSpacing": "0%",
    "lineHeight": "1.375rem"
  },
  "17/body": {
    "fontSize": "1.0625rem",
    "letterSpacing": "0%",
    "lineHeight": "1.625rem"
  },
  "17/body28": {
    "fontSize": "1.0625rem",
    "letterSpacing": "0%",
    "lineHeight": "1.75rem"
  },
  "18/title": {
    "fontSize": "1.125rem",
    "letterSpacing": "-0.5%",
    "lineHeight": "1.375rem"
  },
  "20/title": {
    "fontSize": "1.25rem",
    "letterSpacing": "-0.5%",
    "lineHeight": "1.5rem"
  },
  "24/title": {
    "fontSize": "1.5rem",
    "letterSpacing": "-0.5%",
    "lineHeight": "1.75rem"
  },
  "28/title": {
    "fontSize": "28px",
    "letterSpacing": "-1.5%",
    "lineHeight": "34px"
  },
  "32/title": {
    "fontSize": "32px",
    "letterSpacing": "-1.5%",
    "lineHeight": "38px"
  },
  "40/title": {
    "fontSize": "40px",
    "letterSpacing": "-1.5%",
    "lineHeight": "48px"
  },
  "9/caption": {
    "fontSize": "0.5625rem",
    "letterSpacing": "0%",
    "lineHeight": "0.625rem"
  }
} as const satisfies Record<string, TypographyValue>

/** font-weight 이름 → 숫자 */
export const fontWeightMap = {
  "med": 500,
  "reg": 400,
  "semibold": 600
} as const satisfies Record<string, number>

/** 폰트 패밀리 스택 */
export const fontFamily = "'Pretendard Variable', Pretendard, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'"
